alias l="ls -lh --color=always"
alias ll="ls -lah --color=always"
alias p="ping -a"
alias p6="ping6"
alias pssh="parallel-ssh"
alias pscp="parallel-scp"
alias fp="fping"
alias gp="git pull"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
